apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
spec:
  replicas: 2
  selector:
    matchLabels: 
      system: MyReplica
  template:
    metadata:
      labels:
        system: MyReplica
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
