apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: list-pods_demo-sa
  namespace: default
subjects:
- kind: ServiceAccount
  name: demo-sa
  namespace: default
  #apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: list-pods
  apiGroup: rbac.authorization.k8s.io