apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: less-important-pod
    app: less-important-pod
  name: less-important-pod
  namespace: management
spec:
  containers:
  - image: nginx:1.17.6-alpine
    name: less-important-pod
  restartPolicy: Never
  #priorityClassName: # does not have any, i.e., zero
status: {}