apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: not-so-important-pod
    app: not-so-important-pod
  name: not-so-important-pod
  #namespace: default
spec:
  containers:
  - image: nginx:1.17.6-alpine
    name: not-so-important-pod
    ## -----------------------
    resources: 
      requests:
        memory: 1.5Gi
    ## -----------------------
  restartPolicy: Never
  #priorityClassName: # does not have any, i.e., zero
status: {}
